/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author GaoYifei
 */
public class MenuPanel extends javax.swing.JPanel {
    public MainFrame mainFrame;
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapButton = new javax.swing.JLabel();
        playerButton = new javax.swing.JLabel();
        gameButton = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        mapLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1400, 800));

        mapButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/asheIcon.png"))); // NOI18N
        mapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mapButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mapButtonMouseEntered(evt);
            }
        });

        playerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/YasuoIcon.png"))); // NOI18N
        playerButton.setText("jLabel1");
        playerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playerButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playerButtonMouseEntered(evt);
            }
        });

        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/gurdIcon.png"))); // NOI18N
        gameButton.setText("jLabel3");
        gameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gameButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameButtonMouseEntered(evt);
            }
        });

        playerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        playerLabel.setForeground(new java.awt.Color(255, 255, 255));
        playerLabel.setText("Player Information");

        mapLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        mapLabel.setForeground(new java.awt.Color(255, 255, 255));
        mapLabel.setText("Map Info And Rank");

        gameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        gameLabel.setForeground(new java.awt.Color(255, 255, 255));
        gameLabel.setText("Game Stastics");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/League_of_Legends_logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(904, 904, 904)
                        .addComponent(playerLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(playerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(mapButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(mapLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(gameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameLabel)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(gameButton)
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(gameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerButtonMouseClicked
        // TODO add your handling code here:
        mainFrame.changePanel(1);
    }//GEN-LAST:event_playerButtonMouseClicked

    private void mapButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapButtonMouseClicked
        // TODO add your handling code here:
        mainFrame.changePanel(3);
    }//GEN-LAST:event_mapButtonMouseClicked

    private void gameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMouseClicked
        // TODO add your handling code here:
        mainFrame.changePanel(2);
    }//GEN-LAST:event_gameButtonMouseClicked

    private void mapButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapButtonMouseEntered
        // TODO add your handling code here:
        mapButton.setBounds(mapButton.getX() + 5 ,mapButton.getY() + 5, mapButton.getWidth(), mapButton.getHeight());
        mapLabel.setForeground(Color.yellow);
        this.repaint();
    }//GEN-LAST:event_mapButtonMouseEntered

    private void mapButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapButtonMouseExited
        // TODO add your handling code here:
         mapButton.setBounds(mapButton.getX() - 5 ,mapButton.getY() - 5, mapButton.getWidth(), mapButton.getHeight());
         mapLabel.setForeground(Color.white);
         this.repaint();
    }//GEN-LAST:event_mapButtonMouseExited

    private void playerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerButtonMouseEntered
        // TODO add your handling code here:
        playerButton.setBounds(playerButton.getX() + 5 ,playerButton.getY() + 5, playerButton.getWidth(), playerButton.getHeight());
        playerLabel.setForeground(Color.yellow);
        this.repaint();
    }//GEN-LAST:event_playerButtonMouseEntered

    private void playerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerButtonMouseExited
        // TODO add your handling code here:
        playerButton.setBounds(playerButton.getX() - 5 ,playerButton.getY() - 5, playerButton.getWidth(), playerButton.getHeight());
        playerLabel.setForeground(Color.white);
        this.repaint();
    }//GEN-LAST:event_playerButtonMouseExited

    private void gameButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMouseEntered
        // TODO add your handling code here:
        gameButton.setBounds(gameButton.getX() + 5 ,gameButton.getY() + 5, gameButton.getWidth(), gameButton.getHeight());
        gameLabel.setForeground(Color.yellow);
        this.repaint();
    }//GEN-LAST:event_gameButtonMouseEntered

    private void gameButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonMouseExited
        // TODO add your handling code here:
        gameButton.setBounds(gameButton.getX() - 5 ,gameButton.getY() - 5, gameButton.getWidth(), gameButton.getHeight());
        gameLabel.setForeground(Color.white);
        this.repaint();
    }//GEN-LAST:event_gameButtonMouseExited

//    @Override
//    protected void paintComponent(Graphics g) {
//       super.paintComponent(g);
//       BufferedImage myImage = new BufferedImage(5, 5, BufferedImage.TYPE_INT_ARGB);;
//        try{
//           myImage = ImageIO.read(new File("src/pic/menu.png"));} 
//        catch (IOException e) {}
//        //myImage = getScaledImage(myImage,1080,720);
//        
//        g.drawImage(myImage, 0, 0, this);
//    }
//    
//    
//     private BufferedImage getScaledImage(BufferedImage src, int w, int h){
//    int finalw = w;
//    int finalh = h;
//    double factor = 1.0d;
//    if(src.getWidth() > src.getHeight()){
//        factor = ((double)src.getHeight()/(double)src.getWidth());
//        finalh = (int)(finalw * factor);                
//    }else{
//        factor = ((double)src.getWidth()/(double)src.getHeight());
//        finalw = (int)(finalh * factor);
//    }   
//
//    BufferedImage resizedImg = new BufferedImage(finalw, finalh, BufferedImage.TRANSLUCENT);
//    Graphics2D g2 = resizedImg.createGraphics();
//    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
//    g2.drawImage(src, 0, 0, finalw, finalh, null);
//    g2.dispose();
//    return resizedImg;
//}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameButton;
    private javax.swing.JLabel gameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mapButton;
    private javax.swing.JLabel mapLabel;
    private javax.swing.JLabel playerButton;
    private javax.swing.JLabel playerLabel;
    // End of variables declaration//GEN-END:variables
}
